apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test_application_argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GabijaM/argocd_test.git
    targetRevision: HEAD
    path: test
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
